import { WeatherCodeDetails } from '../types';

export const WEATHER_CODES: Record<number, WeatherCodeDetails> = {
  0: {
    code: 0,
    label: 'Clear Sky',
    description: 'Sunny and completely clear sky',
    iconName: 'Sun',
    category: 'clear',
    themeGradient: 'from-amber-500/10 via-sky-500/5 to-blue-50/30',
    cardBg: 'bg-amber-500/5 border-amber-500/20',
  },
  1: {
    code: 1,
    label: 'Mainly Clear',
    description: 'Mostly sunny with faint high clouds',
    iconName: 'SunDim',
    category: 'clear',
    themeGradient: 'from-sky-400/10 via-blue-500/5 to-slate-50/30',
    cardBg: 'bg-sky-400/5 border-sky-400/20',
  },
  2: {
    code: 2,
    label: 'Partly Cloudy',
    description: 'Scattered clouds with periodic sun',
    iconName: 'CloudSun',
    category: 'cloudy',
    themeGradient: 'from-sky-500/10 via-indigo-500/5 to-slate-50/30',
    cardBg: 'bg-sky-500/5 border-sky-500/20',
  },
  3: {
    code: 3,
    label: 'Overcast',
    description: 'Dense cloud cover across the sky',
    iconName: 'Cloud',
    category: 'cloudy',
    themeGradient: 'from-slate-400/10 via-slate-200/20 to-slate-50/40',
    cardBg: 'bg-slate-400/5 border-slate-300/40',
  },
  45: {
    code: 45,
    label: 'Foggy',
    description: 'Thick fog reducing local visibility',
    iconName: 'CloudFog',
    category: 'fog',
    themeGradient: 'from-zinc-400/10 via-slate-200/20 to-slate-50/40',
    cardBg: 'bg-zinc-400/5 border-zinc-300/40',
  },
  48: {
    code: 48,
    label: 'Freezing Fog',
    description: 'Depositing rime fog with icy conditions',
    iconName: 'CloudFog',
    category: 'fog',
    themeGradient: 'from-teal-400/10 via-slate-200/20 to-slate-50/40',
    cardBg: 'bg-teal-400/5 border-teal-300/40',
  },
  51: {
    code: 51,
    label: 'Light Drizzle',
    description: 'Very light fine rain mist',
    iconName: 'CloudDrizzle',
    category: 'drizzle',
    themeGradient: 'from-blue-500/10 via-sky-200/20 to-slate-50/30',
    cardBg: 'bg-blue-500/5 border-blue-400/20',
  },
  53: {
    code: 53,
    label: 'Moderate Drizzle',
    description: 'Continuous steady light rain mist',
    iconName: 'CloudDrizzle',
    category: 'drizzle',
    themeGradient: 'from-blue-600/10 via-sky-200/20 to-slate-50/30',
    cardBg: 'bg-blue-600/5 border-blue-500/20',
  },
  55: {
    code: 55,
    label: 'Dense Drizzle',
    description: 'Heavy damp mist and dense drizzle',
    iconName: 'CloudDrizzle',
    category: 'drizzle',
    themeGradient: 'from-blue-700/10 via-indigo-100/20 to-slate-50/30',
    cardBg: 'bg-blue-700/5 border-blue-600/20',
  },
  56: {
    code: 56,
    label: 'Light Freezing Drizzle',
    description: 'Light drizzle freezing on impact',
    iconName: 'CloudSnow',
    category: 'drizzle',
    themeGradient: 'from-cyan-500/10 via-sky-100/20 to-slate-50/30',
    cardBg: 'bg-cyan-500/5 border-cyan-400/20',
  },
  57: {
    code: 57,
    label: 'Dense Freezing Drizzle',
    description: 'Dense freezing drizzle creating icy paths',
    iconName: 'CloudSnow',
    category: 'drizzle',
    themeGradient: 'from-cyan-600/10 via-sky-100/20 to-slate-50/30',
    cardBg: 'bg-cyan-600/5 border-cyan-500/20',
  },
  61: {
    code: 61,
    label: 'Slight Rain',
    description: 'Gentle light rain shower',
    iconName: 'CloudRain',
    category: 'rain',
    themeGradient: 'from-blue-500/10 via-blue-100/20 to-slate-50/30',
    cardBg: 'bg-blue-500/5 border-blue-400/20',
  },
  63: {
    code: 63,
    label: 'Moderate Rain',
    description: 'Steady rainfall',
    iconName: 'CloudRain',
    category: 'rain',
    themeGradient: 'from-blue-600/15 via-indigo-100/20 to-slate-50/40',
    cardBg: 'bg-blue-600/10 border-blue-500/30',
  },
  65: {
    code: 65,
    label: 'Heavy Rain',
    description: 'Torrential downpour and heavy rain',
    iconName: 'CloudRainWind',
    category: 'rain',
    themeGradient: 'from-blue-700/20 via-indigo-200/25 to-slate-50/50',
    cardBg: 'bg-blue-700/15 border-blue-600/30',
  },
  66: {
    code: 66,
    label: 'Light Freezing Rain',
    description: 'Slight freezing rain forming black ice',
    iconName: 'CloudSnow',
    category: 'rain',
    themeGradient: 'from-cyan-500/15 via-slate-100/20 to-slate-50/40',
    cardBg: 'bg-cyan-500/10 border-cyan-400/30',
  },
  67: {
    code: 67,
    label: 'Heavy Freezing Rain',
    description: 'Heavy freezing rain, treacherous driving',
    iconName: 'CloudSnow',
    category: 'rain',
    themeGradient: 'from-cyan-700/20 via-slate-200/25 to-slate-50/50',
    cardBg: 'bg-cyan-700/15 border-cyan-500/30',
  },
  71: {
    code: 71,
    label: 'Slight Snow Fall',
    description: 'Light flurries and gentle snowfall',
    iconName: 'Snowflake',
    category: 'snow',
    themeGradient: 'from-sky-300/15 via-slate-100/20 to-slate-50/30',
    cardBg: 'bg-sky-300/10 border-sky-300/30',
  },
  73: {
    code: 73,
    label: 'Moderate Snow Fall',
    description: 'Steady accumulating snowfall',
    iconName: 'Snowflake',
    category: 'snow',
    themeGradient: 'from-sky-400/20 via-slate-100/20 to-slate-50/40',
    cardBg: 'bg-sky-400/15 border-sky-400/30',
  },
  75: {
    code: 75,
    label: 'Heavy Snow Fall',
    description: 'Intense snow blizzard and heavy accumulation',
    iconName: 'Snowflake',
    category: 'snow',
    themeGradient: 'from-blue-300/25 via-slate-200/25 to-slate-50/50',
    cardBg: 'bg-blue-300/20 border-blue-300/40',
  },
  77: {
    code: 77,
    label: 'Snow Grains',
    description: 'Fine icy snow particles',
    iconName: 'Snowflake',
    category: 'snow',
    themeGradient: 'from-slate-300/15 via-slate-100/20 to-slate-50/30',
    cardBg: 'bg-slate-300/10 border-slate-300/30',
  },
  80: {
    code: 80,
    label: 'Slight Rain Showers',
    description: 'Passing light rain showers',
    iconName: 'CloudRain',
    category: 'rain',
    themeGradient: 'from-sky-500/15 via-blue-100/20 to-slate-50/30',
    cardBg: 'bg-sky-500/10 border-sky-400/30',
  },
  81: {
    code: 81,
    label: 'Moderate Rain Showers',
    description: 'Intermittent heavy rain bursts',
    iconName: 'CloudRain',
    category: 'rain',
    themeGradient: 'from-blue-600/20 via-indigo-100/25 to-slate-50/40',
    cardBg: 'bg-blue-600/15 border-blue-500/30',
  },
  82: {
    code: 82,
    label: 'Violent Rain Showers',
    description: 'Extremely heavy sudden rain bursts',
    iconName: 'CloudRainWind',
    category: 'rain',
    themeGradient: 'from-indigo-600/25 via-purple-100/25 to-slate-50/50',
    cardBg: 'bg-indigo-600/20 border-indigo-500/30',
  },
  85: {
    code: 85,
    label: 'Slight Snow Showers',
    description: 'Brief light snow bursts',
    iconName: 'Snowflake',
    category: 'snow',
    themeGradient: 'from-sky-300/15 via-slate-100/20 to-slate-50/30',
    cardBg: 'bg-sky-300/10 border-sky-300/30',
  },
  86: {
    code: 86,
    label: 'Heavy Snow Showers',
    description: 'Sudden heavy snow squalls',
    iconName: 'Snowflake',
    category: 'snow',
    themeGradient: 'from-blue-300/20 via-slate-200/25 to-slate-50/40',
    cardBg: 'bg-blue-300/15 border-blue-300/30',
  },
  95: {
    code: 95,
    label: 'Thunderstorm',
    description: 'Thunderstorm with lightning and rain',
    iconName: 'CloudLightning',
    category: 'thunderstorm',
    themeGradient: 'from-amber-500/20 via-purple-100/25 to-slate-50/50',
    cardBg: 'bg-amber-500/15 border-amber-400/30',
  },
  96: {
    code: 96,
    label: 'Thunderstorm with Hail',
    description: 'Thunderstorm with small hail stones',
    iconName: 'CloudLightning',
    category: 'thunderstorm',
    themeGradient: 'from-amber-600/25 via-violet-100/25 to-slate-50/50',
    cardBg: 'bg-amber-600/15 border-amber-500/30',
  },
  99: {
    code: 99,
    label: 'Severe Hail Thunderstorm',
    description: 'Severe thunderstorm with heavy hail risk',
    iconName: 'CloudLightning',
    category: 'thunderstorm',
    themeGradient: 'from-rose-600/25 via-purple-100/30 to-slate-50/60',
    cardBg: 'bg-rose-600/15 border-rose-500/30',
  },
};

export function getWeatherCodeDetails(code: number, isNight: boolean = false): WeatherCodeDetails {
  const details = WEATHER_CODES[code] || {
    code,
    label: 'Weather Condition',
    description: 'Current local weather state',
    iconName: 'Cloud',
    category: 'cloudy' as const,
    themeGradient: 'from-slate-700/20 via-slate-900/20 to-slate-950/50',
    cardBg: 'bg-slate-700/10 border-slate-700/20',
  };

  if (isNight && (code === 0 || code === 1 || code === 2)) {
    return {
      ...details,
      label: code === 0 ? 'Clear Night' : details.label,
      iconName: code === 0 ? 'Moon' : 'CloudMoon',
      themeGradient: 'from-indigo-950/50 via-slate-900/40 to-slate-950/80',
    };
  }

  return details;
}
